### ISSUE TITLE
Create a database for V1-V3 

### ISSUE THREAD

**Issue by PFRoux** [taolonglab/himapdb#2]
Dear Igor,

Is there a way to create myself a local HiMap database using a set of primers not available in the release you provide ?

I am indeed working with V1-V3 16S data.

Thanks a lot for your help.

Pef

**Comment by igor25** [comment]
Yes, it's present in the "development" version of the HiMAP (that has few other extra features that I am testing) and there _may_ be few bugs here and there (being tested on V1-V3 datasets now). You can install it using:

```
devtools::install_github('taolonglab/himap', ref='dev')
```

**Comment by PFRoux** [comment]
Thanks a lot ! 
I am going to give a try and keep you posted.

Cheers !

Pef

**Comment by PFRoux** [comment]
It worked like a charm and I didn't notice any error / suspicious behavior. Thanks a lot !
